backend:
  name: git
  repo: Rizvan337/sampleqr
  branch: main
  auth_token: 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

media_folder: "docs"
public_folder: "/docs"

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "docs"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }